#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Getopt-Long-Modern
Version  : 1.000
Release  : 6
URL      : https://cpan.metacpan.org/authors/id/D/DB/DBOOK/Getopt-Long-Modern-1.000.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/D/DB/DBOOK/Getopt-Long-Modern-1.000.tar.gz
Summary  : 'Use Getopt::Long with modern defaults'
Group    : Development/Tools
License  : Artistic-2.0
Requires: perl-Getopt-Long-Modern-license = %{version}-%{release}
Requires: perl-Getopt-Long-Modern-perl = %{version}-%{release}
BuildRequires : buildreq-cpan

%description
NAME
Getopt::Long::Modern - Use Getopt::Long with modern defaults
SYNOPSIS
use Getopt::Long::Modern;
GetOptions(
"f|foo=i" => \my $foo,
"b|bar"   => \my $bar,
"Z|baz=s" => \my @baz,
);

%package dev
Summary: dev components for the perl-Getopt-Long-Modern package.
Group: Development
Provides: perl-Getopt-Long-Modern-devel = %{version}-%{release}
Requires: perl-Getopt-Long-Modern = %{version}-%{release}

%description dev
dev components for the perl-Getopt-Long-Modern package.


%package license
Summary: license components for the perl-Getopt-Long-Modern package.
Group: Default

%description license
license components for the perl-Getopt-Long-Modern package.


%package perl
Summary: perl components for the perl-Getopt-Long-Modern package.
Group: Default
Requires: perl-Getopt-Long-Modern = %{version}-%{release}

%description perl
perl components for the perl-Getopt-Long-Modern package.


%prep
%setup -q -n Getopt-Long-Modern-1.000
cd %{_builddir}/Getopt-Long-Modern-1.000

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Getopt-Long-Modern
cp %{_builddir}/Getopt-Long-Modern-1.000/LICENSE %{buildroot}/usr/share/package-licenses/perl-Getopt-Long-Modern/c7096dd0e985e72164c7d91e337e44f13495ce70
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Getopt::Long::Modern.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Getopt-Long-Modern/c7096dd0e985e72164c7d91e337e44f13495ce70

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.34.0/Getopt/Long/Modern.pm
